"use client";

// Dev-only landing page for links generated by scripts/dev-magic-link.mjs.
// admin.generateLink returns tokens in the URL hash fragment (implicit
// flow), unlike the real email magic-link which uses PKCE (?code=) handled
// by src/app/auth/callback/route.ts. @supabase/ssr hardcodes flowType:
// "pkce" for its clients, which means the built-in detectSessionInUrl
// logic only looks for ?code= and ignores #access_token= hash fragments.
// So this page parses the hash itself and calls setSession explicitly.
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function DevSessionPage() {
  const router = useRouter();
  const [errorMsg, setErrorMsg] = useState("");

  useEffect(() => {
    const hash = new URLSearchParams(window.location.hash.slice(1));
    const access_token = hash.get("access_token");
    const refresh_token = hash.get("refresh_token");

    if (!access_token || !refresh_token) {
      setErrorMsg("Ingen session hittades i länken.");
      return;
    }

    const supabase = createClient();
    supabase.auth.setSession({ access_token, refresh_token }).then(({ error }) => {
      if (error) setErrorMsg(error.message);
      else router.replace("/");
    });
  }, [router]);

  return (
    <div className="flex min-h-screen items-center justify-center bg-stone-50 px-4">
      <p className="text-sm text-stone-600">{errorMsg || "Loggar in…"}</p>
    </div>
  );
}
